Repository 9oormthon-univ-dmu/GFD-Mobile, pull requests merged in 2024-09, with the labels that each got.

#16 [Mobile/Full-Stack] 4week/huiwoo-jo
  4week/huiwoo-jo/4week; task and coding-test.md
  4week/huiwoo-jo/TodoApp/index.html
  4week/huiwoo-jo/TodoApp/script.js
  4week/huiwoo-jo/TodoApp/style.css
  4week/huiwoo-jo/githubFinder/app.js
  4week/huiwoo-jo/githubFinder/github.js
  4week/huiwoo-jo/githubFinder/index.html
  4week/huiwoo-jo/githubFinder/ui.js
Labels: GFD, 🩵희우, 4주차

#15 [Mobile/Full-Stack] 4week/seungwon-woo
  4week/seungwon-woo/4week; codingTest.md
  4week/seungwon-woo/codingTest/chapter1.java
  4week/seungwon-woo/codingTest/chapter2.java
Labels: GFD, 💛승원, 4주차

#18 [Mobile/Full-Stack] 5week/seungwon-woo
  5week/seungwon-woo/5week; flutter.md
Labels: GFD, 💛승원, 5주차

#19 [Mobile/Full-Stack] 5week/huiwoo-jo
  5week/huiwoo-jo/Readme.md
  5week/huiwoo-jo/app/.gitignore
  5week/huiwoo-jo/app/build.gradle.kts
  5week/huiwoo-jo/app/proguard-rules.pro
  5week/huiwoo-jo/app/src/androidTest/java/com/brake/composetemplate/ExampleInstrumentedTest.kt
  5week/huiwoo-jo/app/src/main/AndroidManifest.xml
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/MainActivity.kt
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/WeekFirst/BoxActivity.kt
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/WeekFirst/BoxWithConstraintsActivity.kt
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/WeekFirst/ButtonActivity.kt
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/WeekFirst/Extensions.kt
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/WeekFirst/TextActivity.kt
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/ui/theme/Color.kt
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/ui/theme/Theme.kt
  5week/huiwoo-jo/app/src/main/java/com/brake/composetemplate/ui/theme/Type.kt
  5week/huiwoo-jo/app/src/main/res/drawable/ic_launcher_background.xml
  5week/huiwoo-jo/app/src/main/res/drawable/ic_launcher_foreground.xml
  5week/huiwoo-jo/app/src/main/res/font/pretendard.xml
  5week/huiwoo-jo/app/src/main/res/font/pretendard_bold.otf
  5week/huiwoo-jo/app/src/main/res/font/pretendard_medium.otf
  5week/huiwoo-jo/app/src/main/res/font/pretendard_regular.otf
  5week/huiwoo-jo/app/src/main/res/font/pretendard_semibold.otf
  5week/huiwoo-jo/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  5week/huiwoo-jo/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  5week/huiwoo-jo/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  5week/huiwoo-jo/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  5week/huiwoo-jo/app/src/main/res/values/colors.xml
  5week/huiwoo-jo/app/src/main/res/values/strings.xml
  5week/huiwoo-jo/app/src/main/res/values/themes.xml
  5week/huiwoo-jo/app/src/main/res/xml/backup_rules.xml
  5week/huiwoo-jo/app/src/main/res/xml/data_extraction_rules.xml
  5week/huiwoo-jo/app/src/test/java/com/brake/composetemplate/ExampleUnitTest.kt
  5week/huiwoo-jo/build.gradle.kts
  5week/huiwoo-jo/gradle.properties
  5week/huiwoo-jo/gradle/wrapper/gradle-wrapper.properties
  5week/huiwoo-jo/gradlew
  5week/huiwoo-jo/gradlew.bat
  5week/huiwoo-jo/homework/gitkeep
  5week/huiwoo-jo/homework/week1.md
  5week/huiwoo-jo/img/homework1.png
  5week/huiwoo-jo/img/homework2.png
  5week/huiwoo-jo/img/homework3.png
  5week/huiwoo-jo/img/homework4.png
  5week/huiwoo-jo/settings.gradle.kts
Labels: GFD, 🩵희우, 5주차

#21 [Mobile/Full-Stack] 6week/seungwon-woo
  6week/seungwon-woo/6week; flutter.md
  6week/seungwon-woo/img/flutter_lifecycle.png
Labels: GFD, 💛승원, 6주차
