Repository 9oormthon-univ-dmu/GFD-Mobile, pull requests merged in 2024-08, with the labels that each got.

#3 [Moblie/Full-Stack] 1week/huiwoo-jo
  .DS_Store
  .gitignore
  .idea/.gitignore
  1week/huiwoo-jo/1week; design-pattern.md
  1week/huiwoo-jo/MVC.png
  1week/huiwoo-jo/MVI.png
  1week/huiwoo-jo/MVP.png
  1week/huiwoo-jo/MVVM.png
  1week/huiwoo-jo/design-pattern.png
  README.md
Labels: GFD, 1주차, 🩵희우

#5 [Mobile/Full-Stack] 1week/seungwon-woo
  1week/seungwon-woo/MVC-Process.svg
  1week/seungwon-woo/Model-View-Controller.md
Labels: GFD, 1주차, 💛승원

#7 [Mobile/Full-Stack] 2week/seungwon-woo
  2week/seungwon-woo/2week; coding_test.md
  2week/seungwon-woo/image/01.png
  2week/seungwon-woo/image/02.JPG
  2week/seungwon-woo/image/03.JPG
  2week/seungwon-woo/programmers/181928. 이어 붙인 수/README.md
  2week/seungwon-woo/programmers/181928. 이어 붙인 수/이어 붙인 수.java
  2week/seungwon-woo/programmers/181929. 원소들의 곱과 합/README.md
  2week/seungwon-woo/programmers/181929. 원소들의 곱과 합/원소들의 곱과 합.java
  2week/seungwon-woo/programmers/181930. 주사위 게임 2/README.md
  2week/seungwon-woo/programmers/181930. 주사위 게임 2/주사위 게임 2.java
  2week/seungwon-woo/programmers/181931. 등차수열의 특정한 항만 더하기/README.md
  2week/seungwon-woo/programmers/181931. 등차수열의 특정한 항만 더하기/등차수열의 특정한 항만 더하기.java
  2week/seungwon-woo/programmers/181932. 코드 처리하기/README.md
  2week/seungwon-woo/programmers/181932. 코드 처리하기/코드 처리하기.java
  2week/seungwon-woo/programmers/181933. flag에 따라 다른 값 반환하기/README.md
  2week/seungwon-woo/programmers/181933. flag에 따라 다른 값 반환하기/flag에 따라 다른 값 반환하기.java
  2week/seungwon-woo/programmers/181934. 조건 문자열/README.md
  2week/seungwon-woo/programmers/181934. 조건 문자열/조건 문자열.java
  2week/seungwon-woo/programmers/181935. 홀짝에 따라 다른 값 반환하기/README.md
  2week/seungwon-woo/programmers/181935. 홀짝에 따라 다른 값 반환하기/홀짝에 따라 다른 값 반환하기.java
  2week/seungwon-woo/programmers/181936. 공배수/README.md
  2week/seungwon-woo/programmers/181936. 공배수/공배수.java
  2week/seungwon-woo/programmers/181937. n의 배수/README.md
  2week/seungwon-woo/programmers/181937. n의 배수/n의 배수.java
  2week/seungwon-woo/programmers/181938. 두 수의 연산값 비교하기/README.md
  2week/seungwon-woo/programmers/181938. 두 수의 연산값 비교하기/두 수의 연산값 비교하기.java
  2week/seungwon-woo/programmers/181939. 더 크게 합치기/README.md
  2week/seungwon-woo/programmers/181939. 더 크게 합치기/더 크게 합치기.java
  2week/seungwon-woo/programmers/181940. 문자열 곱하기/README.md
  2week/seungwon-woo/programmers/181940. 문자열 곱하기/문자열 곱하기.java
  2week/seungwon-woo/programmers/181941. 문자 리스트를 문자열로 변환하기/README.md
  2week/seungwon-woo/programmers/181941. 문자 리스트를 문자열로 변환하기/문자 리스트를 문자열로 변환하기.java
  2week/seungwon-woo/programmers/181942. 문자열 섞기/README.md
  2week/seungwon-woo/programmers/181942. 문자열 섞기/문자열 섞기.java
  2week/seungwon-woo/programmers/181943. 문자열 겹쳐쓰기/README.md
  2week/seungwon-woo/programmers/181943. 문자열 겹쳐쓰기/문자열 겹쳐쓰기.java
  2week/seungwon-woo/programmers/181944. 홀짝 구분하기/README.md
  2week/seungwon-woo/programmers/181944. 홀짝 구분하기/홀짝 구분하기.java
  2week/seungwon-woo/programmers/181945. 문자열 돌리기/README.md
  2week/seungwon-woo/programmers/181945. 문자열 돌리기/문자열 돌리기.java
  2week/seungwon-woo/programmers/181946. 문자열 붙여서 출력하기/README.md
  2week/seungwon-woo/programmers/181946. 문자열 붙여서 출력하기/문자열 붙여서 출력하기.java
  2week/seungwon-woo/programmers/181947. 덧셈식 출력하기/README.md
  2week/seungwon-woo/programmers/181947. 덧셈식 출력하기/덧셈식 출력하기.java
  2week/seungwon-woo/programmers/181948. 특수문자 출력하기/README.md
  2week/seungwon-woo/programmers/181948. 특수문자 출력하기/특수문자 출력하기.java
  2week/seungwon-woo/programmers/181949. 대소문자 바꿔서 출력하기/README.md
  2week/seungwon-woo/programmers/181949. 대소문자 바꿔서 출력하기/대소문자 바꿔서 출력하기.java
  2week/seungwon-woo/programmers/181950. 문자열 반복해서 출력하기/README.md
  2week/seungwon-woo/programmers/181950. 문자열 반복해서 출력하기/문자열 반복해서 출력하기.java
  2week/seungwon-woo/programmers/181951. a와 b 출력하기/README.md
  2week/seungwon-woo/programmers/181951. a와 b 출력하기/a와 b 출력하기.java
  2week/seungwon-woo/programmers/181952. 문자열 출력하기/README.md
  2week/seungwon-woo/programmers/181952. 문자열 출력하기/문자열 출력하기.java
Labels: GFD, 💛승원, 2주차

#8 [Mobile/Full-Stack] 2week/huiwoo-jo
  2week/huiwoo-jo/2week; coding-test.md
  2week/huiwoo-jo/programmers/12914. 멀리 뛰기/README.md
  2week/huiwoo-jo/programmers/12914. 멀리 뛰기/멀리 뛰기.kt
  2week/huiwoo-jo/programmers/12945. 피보나치 수/README.md
  2week/huiwoo-jo/programmers/12945. 피보나치 수/피보나치 수.kt
  2week/huiwoo-jo/programmers/12985. 예상 대진표/README.md
  2week/huiwoo-jo/programmers/12985. 예상 대진표/예상 대진표.kt
  2week/huiwoo-jo/programmers/154539. 뒤에 있는 큰 수 찾기/README.md
  2week/huiwoo-jo/programmers/154539. 뒤에 있는 큰 수 찾기/뒤에 있는 큰 수 찾기.kt
  2week/huiwoo-jo/programmers/76502. 괄호 회전하기/README.md
  2week/huiwoo-jo/programmers/76502. 괄호 회전하기/괄호 회전하기.kt
Labels: GFD, 🩵희우, 2주차
